# Generated by Django 2.2.6 on 2019-10-28 02:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('clocked_in', models.BooleanField(default=False)),
                ('current_shift', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('time_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('clock_in', models.DateTimeField(default=datetime.datetime.now, verbose_name='Clock In')),
                ('clock_out', models.DateTimeField(blank=True, null=True, verbose_name='Clock Out')),
                ('late', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timely_backend.EmployeeProfile')),
            ],
        ),
    ]
